# Generated by Django 3.1.5 on 2021-01-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type_select',
            field=models.CharField(choices=[('Article', 'Статья'), ('News', 'Новость')], default='News', max_length=32),
        ),
    ]
